version: '3.2'
volumes:
  postgres-data:
  db-data:
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    stdin_open: true
    tty: true
    volumes:
      - .:/usr/src/app
      - ./config/database.yml.dist:/usr/src/app/config/database.yml
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: postgres:9.6
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=redmine_development
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres